In [3]:
a= 7 + 9

print(7 + 9)

16


In [39]:
def factorial(a):
  result=1
  for i in range(1, a+1):
    result *=i
  return result
print(factorial(4))

24


In [49]:
import math

def fact(d):
  return(math.factorial(d))
d=7
y = fact(d)
print(f"the factorial of {d} is {y}")

the factorial of 7 is 5040


In [53]:
import  numpy
n=5
x=numpy.prod([i for i in range(1, n+1)])
x

120

In [56]:
def interestrate(x):
  x= x+0.1*x
  return x
print(interestrate(10))

11.0


In [59]:
def simple_interest(p , t, r):
  int_per_yera=(p * r )/100
  total_int = int_per_yera * t
  return total_int

print(simple_interest(100, 5 , 5))

25.0


In [64]:
def comp_int(p, r ,t):
    paisy = p
    paisy = paisy*(pow(1+ r/100, t)) - p
    return paisy

print(comp_int(100, 10, 2))


21.000000000000014


In [104]:
import numpy as np
def prime_num(star, arra):
  arrb=[]
  prime = False
  for i in range(star, arra+1):
    for j in range(2, i):
      if i%j ==0:
        prime = True
        break
      else:
        prime = False
    if(prime== False):
      arrb.append(i)
  return arrb
star=2
arra=120
print(prime_num(star,arra))

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113]


In [107]:
def is_prime():
  x = int(input())
  res = prime_num(x,x)
  print(res)
  if x in res:
    print("prime")
  else:
    print("not prime")
print(is_prime())

3
[3]
prime
None


In [122]:
def fab(s):
    ali = []
    if s <= 0:
        return ali
    elif s == 1:
        ali.append(0)
        return ali
    elif s == 2:
        ali.extend([0, 1])
        return ali
    else:
        ali.extend([0, 1])  # Initialize the list with the first two Fibonacci numbers
        for i in range(2, s):
            next_fib = ali[-1] + ali[-2]  # Calculate the next Fibonacci number
            ali.append(next_fib)
        return ali

s = int(input("Write the Fibonacci number you want to find: "))
fib_list = fab(s)
print(fib_list)


Write the Fibonacci number you want to find: 5
[0, 1, 1, 2, 3]


Numpy

In [125]:
import numpy as np
print(np.__version__)
np.show_config()

1.22.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [128]:
x= np.zeros(10)
y = np.ones(10)
print(x, y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [131]:
z= np.ones((10,10))
print(z)
print("%d bytes" % (z.size * z.itemsize))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
800 bytes


In [137]:
x = np.arange(10,50)
print(x)
x = x[:: -1]
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [139]:
x = np.arange(9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [143]:
x = np.nonzero([1, 0, 3, 4])
print(x)

(array([0, 2, 3]),)


In [145]:
x= np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [146]:
x= np.random.random((3,3,3))
print(x)

[[[0.3978688  0.52464918 0.9357382 ]
  [0.72004184 0.51340299 0.81614572]
  [0.47648442 0.93538714 0.47177212]]

 [[0.1875347  0.9334087  0.88189663]
  [0.1633488  0.61289986 0.24642903]
  [0.09850566 0.98675447 0.35352974]]

 [[0.80975412 0.150022   0.55669843]
  [0.36502877 0.79370356 0.88838111]
  [0.69271532 0.58927981 0.25777971]]]


In [149]:
x =  np.random.random((10,10))
xmin , xmax = x.min(), x.max()
print(xmin, xmax)

0.00624912739636696 0.9973043199093564


In [150]:
x = np.random.random(30)
xmean = x.mean()
print(xmean)

0.5643706110057174


In [151]:
x= np.ones((10,10))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [152]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [154]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [157]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
